-- Wygonin 2027: kandydat na tygodniowy wyjazd w maju. Termin i stanowisko pozostają do ustalenia.
UPDATE trips
SET name='Wygonin 2027', lake='Jezioro Wygonin', country='Polska', status='planning',
    start_at=NULL, end_at=NULL, peg='Do wyboru', latitude=53.95598, longitude=18.13111,
    facts_json='{"tripState":"Planowanie – tydzień w maju 2027","waterSize":"ok. 68 ha","depth":"1–24.8 m; otwarta woda do ok. 20 m, zatoka 25–34 do 4.5 m","carpRecord":"30.35 kg wg aktualnej karty BookingFish","rods":"typowe pakiety 3 wędki/os.; regulamin dopuszcza maks. 4 po zgłoszeniu","baitBoat":"dozwolone modele RC","boat":"łódź/ponton dozwolone; kamizelka obowiązkowa","power":"tylko Przystań Wygonin – brak prądu na stanowiskach","toilets":"toalety na stanowiskach + Toi Toi na parkingu; prysznic na Przystani","season":"01.04–16.11","address":"Wygonin 12c, pomorskie","shops":"sklep Wygonin ok. 300 m; market ok. 5 km","food":"Karczma pod Klonami ok. 300 m; Oberża ok. 3 km","access":"1–14,17,18 przeprawa łodzią; 15,16 rozładunek autem; 19–34 dojazd autem","reservation":"rezerwacje kolejnego roku zwykle od 01.10; pierwszeństwo pobyt min. tydzień","researchUpdated":"2026-09-03"}',
    updated_at=CURRENT_TIMESTAMP
WHERE id='poland-2027';

DELETE FROM trip_documents WHERE trip_id='poland-2027';
INSERT INTO trip_documents(trip_id,kind,title,content,source_url,sort_order) VALUES
('poland-2027','overview','Wygonin – charakter łowiska','Naturalne jezioro rynnowe ok. 68 ha. Bardzo zróżnicowane: otwarta woda na stanowiskach 1–24 z głębiami dochodzącymi do ok. 20 m oraz ok. 18-hektarowa, płytsza i mocniej zarośnięta zatoka na stanowiskach 25–34, do ok. 4,5 m. Występują twarde blaty, spady, głębie, roślinność i zatopione drzewa. To techniczna woda, na której nie należy bać się łowienia głęboko.','https://bookingfish.eu/lowiska/jezioro-wygonin',10),
('poland-2027','rules','Regulamin – zestawy i wędki','Catch & release. Maksymalnie 4 wędki na osobę, ale aktualne pakiety tygodniowe obejmują 3 wędki/os. i liczbę wędek trzeba zgłosić przy rezerwacji. Karp wyłącznie metodą gruntową. Maksymalna wywózka 200 m. Bezpieczny klips/drop-off obowiązkowy. Plecionka zabroniona jako linka główna i strzałówka; dopuszczona jako materiał przyponowy. Leadcore maks. 1,5 m. Jeden hak na zestaw, rozmiar od 6 do 1; zalecany mikro-zadzior.','https://bookingfish.eu/lowiska/jezioro-wygonin',20),
('poland-2027','rules','Regulamin – nęcenie i ryby','Zakaz nęcenia suchym lub źle ugotowanym ziarnem, szczególnie surowym orzechem tygrysim. Ryby >20 kg fotografowane w wodzie i zgłaszane opiekunowi. Zakaz fotografowania ryb na stojąco. CarpCare obowiązkowy. Matę i worek należy zwilżyć. Nie wolno przetrzymywać karpi w workach poza oczekiwaniem na opiekuna. Złowionego suma należy zgłosić i nie wolno wypuścić go z powrotem.','https://bookingfish.eu/lowiska/jezioro-wygonin',30),
('poland-2027','equipment','Sprzęt obowiązkowy','Podbierak minimum 42 cali; worek do ważenia ze sztywnymi ramionami; duża mata/wanna minimum 5 cm grubości z piankowymi lub pompowanymi bokami albo kołyska ze sztywnymi bokami; środek CarpCare. Na łodzi/pontonie bezwarunkowo kamizelka ratunkowa. Namiot zielony, brązowy lub camo.','https://bookingfish.eu/lowiska/jezioro-wygonin',40),
('poland-2027','logistics','Stanowiska i przeprawa','Stanowiska 1–14 oraz 17–18 są dostępne tylko przeprawą łodzią. 15–16: autem tylko rozładunek/załadunek, później auto za szlaban. Na 19–34 auto może pozostać przy stanowisku, bez blokowania przejazdu. Przeprawę trzeba zgłosić minimum 2 dni wcześniej. Na stanowiskach nie ma prądu. Woda pitna dostępna na Przystani.','https://bookingfish.eu/lowiska/jezioro-wygonin',50),
('poland-2027','strategy','Strategia – maj','Maj powinien być traktowany elastycznie: zacząć od obserwacji wody i temperatury, a nie od stałej głębokości. W cieplejsze, słoneczne okresy sprawdzać płytszą zatokę, krawędzie roślinności i blaty; przy ochłodzeniu lub stabilnej chłodnej wodzie kontrolować spady i głębsze półki. Na Wygoninie karpie regularnie łowione są także na 10–12 m. Ograniczyć zbędne pływanie i markery; precyzyjne, małe punkty nęcenia mogą być lepsze niż szerokie dywany. Orzech tygrysi ma dobrą lokalną opinię, ale musi być prawidłowo przygotowany.','https://www.carpwars.pl/eliminacje-wygonin/',60),
('poland-2027','reservation','Rezerwacja 2027','Według obecnego regulaminu rezerwacje na kolejny rok zaczynają się 1 października roku poprzedzającego, chyba że manager ustali inaczej. W pierwszej kolejności przyjmowane są pobyty minimum tygodniowe. Dla Patryka i Maćka tygodniowy majowy wyjazd pasuje więc do pierwszego okna rezerwacyjnego. Termin i stanowisko nie są jeszcze wybrane.','https://bookingfish.eu/lowiska/jezioro-wygonin',70),
('poland-2027','facilities','Zaplecze i okolica','Prysznic i WC na Przystani; toalety również na stanowiskach i Toi Toi na parkingu. Prąd wyłącznie na Przystani. Sklep w Wygoninie ok. 300 m, market ok. 5 km. Karczma pod Klonami ok. 300 m, Oberża ok. 3 km. Przystań Wygonin ok. 50 m od łowiska.','https://bookingfish.eu/lowiska/jezioro-wygonin',80);

INSERT OR REPLACE INTO app_settings(key,value,updated_at) VALUES('schema_version','6',CURRENT_TIMESTAMP);