-- Miłoszewskie 2027: osobny kandydat na tygodniowy wyjazd Dream Team w maju 2027.
-- Stanowisko 33 wybrane do przygotowania. Dokładny termin pozostaje do ustalenia.

INSERT OR REPLACE INTO lakes(id,name,country,latitude,longitude,image_url,facts_json,source_url,updated_at)
VALUES(
  'miloszewskie','Jezioro Miłoszewskie','Polska',54.44567,18.04168,NULL,
  '{"presentation":"dynamic","waterType":"naturalne, głębokie jezioro przepływowe","waterSize":"35,6 ha","depth":"średnio 7,2 m · maks. 28 m","rods":"maks. 2 wędki na osobę","baitBoat":"wywózka zestawów i nęcenie ze środków pływających dozwolone do połowy odległości akwenu i możliwie w linii prostej","boat":"środki pływające do sondowania, nęcenia i wywózki zgodnie z regulaminem; łodzie dostępne do wypożyczenia","carpRecord":"duże karpie 30+ kg; przed wyjazdem ponownie zweryfikować aktualny rekord","power":"brak potwierdzonej informacji o 230 V na stanowisku 33 — nie zakładać dostępu","address":"Jezioro Miłoszewskie, okolice Strzepcza i Miłoszewa, pomorskie","season":"karpiarze: 01.04–30.12, całą dobę","fish":"karp, leszcz, okoń, płoć, szczupak, miętus, lin, węgorz, sieja, sielawa, krąp, wzdręga, karaś pospolity","researchUpdated":"2026-09-03"}',
  'https://miloszewskie.pl/',CURRENT_TIMESTAMP
);

INSERT OR REPLACE INTO trips(
  id,year,name,lake,lake_id,country,status,start_at,end_at,peg,latitude,longitude,lake_image,facts_json,is_active,created_at,updated_at
) VALUES(
  'miloszewskie-2027',2027,'Miłoszewskie 2027','Jezioro Miłoszewskie','miloszewskie','Polska','planning',NULL,NULL,'Stanowisko 33',54.44567,18.04168,NULL,
  '{"tripState":"Planowanie – tydzień w maju 2027","fishermen":2,"peg":"33","pegName":"Stanowisko 33","pegAccess":"Według mapy stanowisk przekazanej przez użytkownika stanowisko 33 obsługuje dojazd nr 2. Oficjalna strona potwierdza, że problematyczne bezpośrednie dojazdy dotyczą innych numerów; przed wyjazdem potwierdzić stan drogi z gospodarzem.","pegOrientation":"Północno-zachodnia / północna część jeziora. Sektor otwiera się w stronę głębszej misy jeziora.","pegBathymetry":"Oficjalna mapa batymetryczna pokazuje przed sektorem 32–33 szybkie przejście z przybrzeżnej płycizny przez kolejne izobaty w stronę głębszej misy. Relacje dokładnie ze stanowiska 33 potwierdzają praktyczne łowienie na 8,5 m, 9 m i 10,5 m.","pegPrimaryDepthWindow":"Startowo sprawdzić Deeperem krawędzie i zmiany dna około 6–8 m, następnie potwierdzone relacjami 8,5–10,5 m; jeden zestaw może kontrolować inną warstwę lub ZIG, jeśli ryby są zawieszone.","pegBottom":"Oficjalna mapa twardości wskazuje w tej części mozaikę twardości i przejścia. Nie kopiować koloru mapy jako dokładnego punktu — potwierdzić każdy spot Deeperem.","pegFishingBoundary":"Sondowanie, nęcenie, markery i wywózka ze środka pływającego do połowy odległości akwenu i możliwie w linii prostej; nie wolno utrudniać łowienia sąsiadom.","pegHistory":"Stanowisko 33 ma mocną historię: w maju 2017 po pierwszej nocy prowadziła z niego para z karpiami 11,3 i 10,8 kg; w 2019 udokumentowano tu karpia 28,260 kg; późniejsze relacje opisują 33 jako jedno z topowych, ale wymagających stanowisk.","pegMapConfidence":"Batymetria i twardość pochodzą z oficjalnych map łowiska; szczegóły stanowiska 33 i realne punkty muszą zostać potwierdzone Deeperem na miejscu.","maps":{"stands":"https://miloszewskie.pl/stanowiska/","bathymetry":"https://miloszewskie.pl/batymetria/","bottomHardness":"https://miloszewskie.pl/twardosc/"},"researchUpdated":"2026-09-03"}',
  0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
);

DELETE FROM trip_documents WHERE trip_id='miloszewskie-2027';
INSERT INTO trip_documents(trip_id,kind,title,content,source_url,sort_order) VALUES
('miloszewskie-2027','overview','Miłoszewskie — charakter wody','Jezioro Miłoszewskie leży na północnym krańcu Kaszubskiego Parku Krajobrazowego w pobliżu Strzepcza i Miłoszewa. Oficjalnie: 35,6 ha, średnio 7,2 m, maksymalnie 28 m. Głęboczek leży w centralno-wschodniej części. Zachodni brzeg ma łagodniejsze spady i bardziej muliste dno, wschodni ostrzejsze spady i twardsze, piaszczyste dno. Północ jest miejscami trzcinowa i częściowo porośnięta roślinnością.','https://miloszewskie.pl/opis-jeziora/',10),
('miloszewskie-2027','overview','Stanowisko 33 — dlaczego jest mocne','Stanowisko 33 jest historycznie produktywne. W Pomorskich Mistrzostwach Karpiarzy w maju 2017 para na 33 po pierwszej nocy prowadziła z rybami 11,3 i 10,8 kg mimo zimowej aury. W 2019 na 33 udokumentowano karpia 28,260 kg. Relacje z kolejnych lat określają 33 jako jedno z topowych miejsc, ale pokazują też, że przy zmianie pogody ryby mogą całkowicie opuścić sektor.','https://miloszewskie.pl/pomorskie-mistrzostwa-karpiarzy-2017-czyli-4-pory-roku-w-5-dni/',11),
('miloszewskie-2027','overview','Ryby','Oficjalna lista gatunków obejmuje m.in. karpia, leszcza, okonia, płoć, szczupaka, miętusa, lina, węgorza, sieję, sielawę, krąpia, wzdręgę i karasia pospolitego. Karpie są no-kill.','https://miloszewskie.pl/ryby/',12),

('miloszewskie-2027','rules','Karpiarze — wędki i licencja','Rezerwacja telefoniczna przed przyjazdem. Jezioro dla karpiarzy jest udostępnione od 01.04 do 30.12 przez całą dobę. Doba karpiowa trwa 14:00–12:00, a ostatniego dnia stanowisko należy opuścić do 13:00. Maksymalnie 2 wędki na osobę, czyli Dream Team Patryk + Maciek: maksymalnie 4 wędki łącznie.','https://miloszewskie.pl/regulamin/',20),
('miloszewskie-2027','rules','Linka główna i markery','Plecionka jako linka główna jest zabroniona. Do znakowania łowiska dozwolone są tylko markery tyczkowe; markery typu H są zabronione.','https://miloszewskie.pl/regulamin/',21),
('miloszewskie-2027','rules','Wywózka, sondowanie i granice','Można rozbijać namiot w obrębie stanowiska, sondować, nęcić, stawiać dozwolone markery i wywozić zestawy ze środków pływających do połowy odległości akwenu i możliwie w linii prostej. Nie wolno utrudniać łowienia osobom na sąsiednich stanowiskach.','https://miloszewskie.pl/regulamin/',22),
('miloszewskie-2027','rules','Nęcenie — kluczowy zakaz','Zakaz nęcenia ziarnem surowym i gotowanym: m.in. zwykłą kukurydzą, grochem, orzechem tygrysim i łubinem. Wyjątek: gotowane konopie oraz miękka kukurydza puszkowa. Dobowy limit całej zanęty wynosi 3 kg. Po sesji nie wolno wrzucać do wody niewykorzystanej zanęty.','https://miloszewskie.pl/regulamin/',23),
('miloszewskie-2027','rules','Carp Care','Na stanowisku obowiązkowo mata karpiowa minimum 70 × 120 cm z grubym materacem, duży podbierak i preparat do dezynfekcji ran. Każdą rybę po wyjęciu haka należy zdezynfekować; ryby obsługiwać delikatnie, polewać wodą i nie przedłużać ważenia ani zdjęć.','https://miloszewskie.pl/regulamin/',24),
('miloszewskie-2027','rules','Porządek i ogień','Zakaz rozpalania ognisk, zaśmiecania, niszczenia roślinności i głośnego zachowania. Śmieci po zasiadce trzeba zabrać ze sobą; cennik przewiduje odpłatne pozostawienie worka do wywozu.','https://miloszewskie.pl/regulamin/',25),

('miloszewskie-2027','reservation','Rezerwacja stanowiska 33','Rezerwacje stanowisk tylko telefonicznie. Karol: +48 696 036 236; Grzegorz: +48 602 300 147. Oficjalna strona wyraźnie podaje, że rezerwacji nie wykonuje się e-mailem ani przez social media. Przy rezerwacji od razu potwierdzić stanowisko 33, dokładny majowy termin, liczbę osób, możliwość postawienia dwóch namiotów oraz aktualne zasady dojazdu.','https://miloszewskie.pl/kontakt/',30),
('miloszewskie-2027','reservation','Cena — stan na research 03.09.2026','Oficjalny cennik podaje licencję karpiową no-kill 160 zł za dobę. Łódź z wiosłem 20 zł, silnik elektryczny 30 zł, akumulator 30 zł, mata 10 zł/doba, podbierak 10 zł/doba, kamizelka 10 zł/doba. Przed rezerwacją 2027 sprawdzić ceny ponownie.','https://miloszewskie.pl/cennik/',31),
('miloszewskie-2027','logistics','Meldunek przed łowieniem','Przed rozpoczęciem łowienia należy zameldować się u strażnika w rybaczówce przy stanowisku 23 i uregulować licencję. Numer do rybaczówki podany w oficjalnym cenniku: +48 538 373 450.','https://miloszewskie.pl/cennik/',40),
('miloszewskie-2027','logistics','Dojazd do jeziora','Jezioro leży przy trasie Strzepcz–Miechucino. Oficjalny opis prowadzi przez Strzepcz; po skręcie w kierunku Miechucina po około 250 m jezioro jest widoczne po lewej stronie. W aplikacji nawigacja powinna prowadzić najpierw do jeziora / rybaczówki, bo przed łowieniem wymagany jest meldunek.','https://miloszewskie.pl/dojazd/',41),
('miloszewskie-2027','logistics','Dojazd do stanowiska 33','Na mapie stanowisk przekazanej przez użytkownika stanowiska 15–33 mają dojazd nr 2, więc 33 planujemy przez dojazd nr 2. Oficjalna strona wskazuje szczególne problemy dojazdowe dla 43–44 i 46–47, nie dla 33. Stan drogi do 33 potwierdzić telefonicznie przed wyjazdem, szczególnie po opadach.',NULL,42),
('miloszewskie-2027','facilities','Zakupy i jedzenie','Oficjalna strona podaje sklepy spożywcze w Strzepczu, stację benzynową z podstawowym zaopatrzeniem oraz Pizzerię Mercato, która według strony może dowozić jedzenie nad jezioro. Numery podane przez łowisko: (58) 572 16 72 oraz 516 358 403. Przed wyjazdem sprawdzić aktualność dowozu.','https://miloszewskie.pl/polecane/',43),
('miloszewskie-2027','facilities','Przynęty na miejscu','Przy rybaczówce na stanowisku 23 oficjalna strona informuje o możliwości zakupu przynęt, zanęt, dipów i boosterów B.Baits. Warto traktować to jako awaryjne uzupełnienie i potwierdzić dostępność przed przyjazdem.','https://miloszewskie.pl/polecane/',44),
('miloszewskie-2027','facilities','Łódź i wyposażenie do wypożyczenia','Oficjalny cennik przewiduje wypożyczenie łodzi z wiosłem, silnika elektrycznego, akumulatora, maty, podbieraka i kamizelki. Nie zakładamy jednak dostępności bez rezerwacji — potwierdzić przy rezerwacji stanowiska 33.','https://miloszewskie.pl/cennik/',45),

('miloszewskie-2027','strategy','Stanowisko 33 — mapa dna','Oficjalna batymetria i przekazana mapa pokazują sektor 33 na północno-zachodnim brzegu, skąd dno schodzi w stronę głębszej misy. Nie wybieramy jednego punktu z obrazka. Po przyjeździe robimy wachlarz Deeperem i szukamy: krawędzi spadu, wypłaszczeń, zmiany twardości oraz miejsc, na których zestaw nie zsuwa się po stoku.','https://miloszewskie.pl/batymetria/',50),
('miloszewskie-2027','strategy','Stanowisko 33 — twardość dna','Oficjalna mapa twardości pokazuje zróżnicowane dno i przejścia w sektorze północnym. Najcenniejszy może być nie skrajnie twardy ani skrajnie miękki kolor, lecz wyraźna granica dwóch typów dna. Deeperem potwierdzić każde takie przejście przed położeniem zestawu.','https://miloszewskie.pl/twardosc/',51),
('miloszewskie-2027','strategy','Stanowisko 33 — głębokości potwierdzone relacją','W relacji dokładnie ze stanowiska 33 testowano 8,5 m, 9,0 m i 10,5 m. To daje bardzo dobry zakres startowy do sprawdzenia, ale nie gwarantuje obecności ryb. Przy zmianie pogody w tej samej relacji ryby całkowicie opuściły sektor.','https://karpiowyjanusz.pl/jezioro-miloszewskie-2023r',52),
('miloszewskie-2027','strategy','Maj — historyczne potwierdzenie 33','W zawodach rozpoczętych 10 maja 2017, przy zimowej aurze, stanowisko 33 po pierwszej nocy prowadziło dzięki dwóm karpiom 11,3 i 10,8 kg. To potwierdza, że 33 może produkować ryby również w zimnym maju — nie oznacza jednak, że należy automatycznie łowić na jednej głębokości.','https://miloszewskie.pl/pomorskie-mistrzostwa-karpiarzy-2017-czyli-4-pory-roku-w-5-dni/',53),
('miloszewskie-2027','strategy','Plan 4 wędek — start','Regulamin pozwala maksymalnie na 2 wędki/os., więc startujemy 2+2. Wędka 1: górna / środkowa krawędź znalezionego spadu. Wędka 2: twarde przejście w oknie około 8,5–10,5 m. Wędka 3: druga głębokość lub inny typ dna, aby nie dublować teorii. Wędka 4: mobilna — pod pokazy ryb, zmianę wiatru albo jako ZIG, gdy sonar/obserwacja wskazuje ryby w toni.',NULL,54),
('miloszewskie-2027','strategy','Plan sondowania pierwszej godziny','Najpierw obserwacja powierzchni i kierunku wiatru. Potem 5–7 przejazdów Deeperem wachlarzem z sektora 33. Zaznaczyć głębokości, nachylenie, twardość i ewentualną roślinność. Powtórzyć przejazd przez 3–4 najlepsze miejsca. Dopiero wtedy rozłożyć cztery zestawy. Nie pływać bez potrzeby po całym sektorze.',NULL,55),
('miloszewskie-2027','strategy','ZIG — realny plan B na 33','Stanowisko 33 ma udokumentowane próby i skuteczne sesje z ZIG Rigiem. Gdy ryby pokazują się lub sonar widzi je w toni, a zestawy denne milczą, nie czekamy automatycznie kolejnej doby: jedną mobilną wędkę przeznaczamy na systematyczne sprawdzanie warstw wody.','https://karpiarze.pl/miloszewskie-konie-jak-lowic-karpie-na-zig-riga/',56),
('miloszewskie-2027','strategy','Nęcenie pod regulamin Miłoszewskiego','Nie zabieramy tygrysa jako zanęty — jest zabroniony. Start mały i precyzyjny, z uwzględnieniem limitu 3 kg/dobę. Podstawą mogą być kulki/pellet i dozwolone dodatki; ziarna tylko gotowane konopie i miękka kukurydza puszkowa. Na spadzie małe porcje ograniczają staczanie się pokarmu poza zestaw.','https://miloszewskie.pl/regulamin/',57),
('miloszewskie-2027','strategy','Reakcja na ochłodzenie','Relacja ze stanowiska 33 pokazuje, że po ochłodzeniu ryby mogą wyjść z sektora. Jeśli przez dłuższy czas brak pokazów, sonar nie potwierdza ryb i cztery różne prezentacje milczą, nie dokładamy bezmyślnie zanęty. Najpierw zmiana warstwy / głębokości jednej wędki, obserwacja wiatru i ewentualny ZIG.','https://karpiowyjanusz.pl/jezioro-miloszewskie-2023r',58),
('miloszewskie-2027','strategy','Historyczna duża ryba z 33','W materiale zawodów z 2019 udokumentowano karpia 28,260 kg złowionego na stanowisku 33. Traktujemy to jako dowód potencjału sektora, nie jako aktualną gwarancję trasy ryb.','https://serwer378507.lh.pl/pdf/2020/adder_2020.pdf',59),

('miloszewskie-2027','maps','Mapa stanowisk','Oficjalna mapa numerów stanowisk. Dodatkowo użytkownik przekazał aktualną grafikę, na której 33 leży na północno-zachodnim brzegu i jest przypisane do dojazdu nr 2.','https://miloszewskie.pl/stanowiska/',60),
('miloszewskie-2027','maps','Mapa batymetryczna','Oficjalna mapa batymetryczna jest podstawą planu startowego; realne spoty potwierdzamy Deeperem.','https://miloszewskie.pl/batymetria/',61),
('miloszewskie-2027','maps','Mapa twardości dna','Oficjalna mapa twardości dna służy do wskazania przejść i stref do sprawdzenia, a nie do wpisywania fikcyjnych punktów GPS.','https://miloszewskie.pl/twardosc/',62);

DELETE FROM checklist_items WHERE trip_id='miloszewskie-2027' AND notes LIKE 'AUTO:MIL33:%';
INSERT INTO checklist_items(trip_id,category,label,assigned_to,packed,quantity,notes,sort_order) VALUES
('miloszewskie-2027','Stanowisko 33','Deeper CHIRP+2 + ładowarka',NULL,0,'1','AUTO:MIL33: obowiązkowy plan realnego skanu spadów i twardości',10),
('miloszewskie-2027','Stanowisko 33','Zasilanie awaryjne / stacja powerbank',NULL,0,'1','AUTO:MIL33: brak potwierdzonego 230 V na stanowisku 33 — planować niezależne zasilanie',11),
('miloszewskie-2027','Stanowisko 33','Marker tyczkowy',NULL,0,'1–2','AUTO:MIL33: H-markery zabronione',12),
('miloszewskie-2027','Carp Care','Mata min. 70 × 120 cm z grubym materacem',NULL,0,'1','AUTO:MIL33: wymóg oficjalnego regulaminu',20),
('miloszewskie-2027','Carp Care','Duży podbierak karpiowy',NULL,0,'1+','AUTO:MIL33: wymóg oficjalnego regulaminu',21),
('miloszewskie-2027','Carp Care','Clinik / środek do dezynfekcji ran',NULL,0,'1','AUTO:MIL33: każda ryba po wyjęciu haka ma być zdezynfekowana',22),
('miloszewskie-2027','Łowienie','4 zestawy główne — 2 Patryk + 2 Maciek','Patryk + Maciek',0,'4','AUTO:MIL33: maksymalnie 2 wędki na osobę',30),
('miloszewskie-2027','Łowienie','Żyłka główna — bez plecionki',NULL,0,'4 kołowrotki','AUTO:MIL33: plecionka jako linka główna zabroniona',31),
('miloszewskie-2027','Łowienie','Zestawy denne na twarde przejścia / spad',NULL,0,'kilka','AUTO:MIL33: plan na 8,5–10,5 m po potwierdzeniu Deeperem',32),
('miloszewskie-2027','Łowienie','ZIG Rig — komplet do regulacji głębokości',NULL,0,'1 kpl.','AUTO:MIL33: udokumentowana metoda na stanowisku 33, plan B przy rybach w toni',33),
('miloszewskie-2027','Nęcenie','Gotowane konopie',NULL,0,'wg limitu','AUTO:MIL33: jedno z nielicznych dozwolonych ziaren; całkowity limit zanęty 3 kg/dobę',40),
('miloszewskie-2027','Nęcenie','Miękka kukurydza puszkowa',NULL,0,'wg limitu','AUTO:MIL33: dozwolony wyjątek w regulaminie',41),
('miloszewskie-2027','Nęcenie','NIE BRAĆ tygrysa do nęcenia',NULL,0,'0','AUTO:MIL33: orzech tygrysi jako ziarno do nęcenia jest zabroniony',42),
('miloszewskie-2027','Przyjazd','Zapisane numery: Karol 696 036 236 / Grzegorz 602 300 147',NULL,0,'1','AUTO:MIL33: rezerwacja i kontakt z gospodarzem',50),
('miloszewskie-2027','Przyjazd','Meldunek i opłata w rybaczówce — stanowisko 23',NULL,0,'1','AUTO:MIL33: wymagane przed rozpoczęciem łowienia',51),
('miloszewskie-2027','Przyjazd','Potwierdzić dojazd nr 2 do stanowiska 33',NULL,0,'1','AUTO:MIL33: przed wyjazdem potwierdzić stan drogi i możliwość dojazdu ciężkim autem',52),
('miloszewskie-2027','Przyjazd','Potwierdzić granice sektora 33 z sąsiadami / gospodarzem',NULL,0,'1','AUTO:MIL33: wywózka ma nie utrudniać łowienia z innych stanowisk',53);

INSERT OR REPLACE INTO app_settings(key,value,updated_at)
VALUES('schema_version','14',CURRENT_TIMESTAMP);
